
export type DatabaseTableName =
  | 'policy_documents'
  | 'claim_documents'
  | 'sales_documents'
  | 'client_documents'
  | 'insurer_documents'
  | 'agent_documents'
  | 'addendum_documents'
  | 'invoice_documents'
  | 'activity_logs'
  | 'agent_payouts'
  | 'agents'
  | 'bank_statements'
  | 'bank_transactions'
  | 'claims'
  | 'client_commissions'
  | 'clients'
  | 'commissions'
  | 'companies'
  | 'company_email_settings'
  | 'company_settings'
  | 'fixed_commissions'
  | 'instructions'
  | 'insurance_products'
  | 'insurers'
  | 'invitations'
  | 'invoice_items'
  | 'invoices'
  | 'leads'
  | 'manual_commissions'
  | 'payout_items'
  | 'policies'
  | 'policy_addendums'
  | 'policy_types'
  | 'profiles'
  | 'report_schedules'
  | 'sales_assignments'
  | 'sales_processes'
  | 'saved_filters'
  | 'saved_reports'
  | 'unlinked_payments'
  | 'user_custom_privileges';

export type RelationName = DatabaseTableName;
